"""Shared runner constants."""

from __future__ import annotations

from typing import Final

SCHEMA_VERSION: Final = 1
RUNNER_SOURCE: Final = "rlab._runner"

STRICT_ENV_VAR: Final = "RLAB_RUNNER_STRICT"
STRICT_ENABLED: Final = "1"
STRICT_DISABLED: Final = "0"

ENCODING: Final = "utf-8"
ERRORS_REPLACE: Final = "replace"
JSON_NEWLINE: Final = "\n"
JSON_INDENT: Final = 2
JSON_SEPARATORS: Final = (",", ":")
CSV_WRITE_MODE: Final = "w"

PATH_PARENT: Final = ".."
REF_SEPARATOR: Final = ":"
PATH_SEPARATORS: Final = ("/", "\\", PATH_PARENT)

EVENT_COMPLETED: Final = "completed"
EVENT_FAILED: Final = "failed"
EVENT_REGISTRY_RECORD: Final = "registry_record"
EVENT_METRIC: Final = "metric"
EVENT_BATCH: Final = "batch"
EVENT_LOG: Final = "log"
EVENT_ARTIFACT: Final = "artifact"

COMMAND_EXECUTE: Final = "execute"

KIND_DATASET: Final = "dataset"
KIND_STUDY: Final = "study"
KIND_WORKFLOW: Final = "workflow"
KIND_WORKFLOW_STEP: Final = "workflow_step"
KIND_EXPERIMENT: Final = "experiment"
KIND_DATASET_SOURCE: Final = "dataset_source"
KIND_DATASET_SINK: Final = "dataset_sink"
KIND_LOADER: Final = "loader"
KIND_TRANSFORM: Final = "transform"
KIND_DEDUP: Final = "dedup"
KIND_GROUP: Final = "group"
KIND_FILE: Final = "file"
KIND_TABLE: Final = "table"
KIND_LOG: Final = "log"

ACTION_DROP: Final = "drop"
ACTION_KEEP: Final = "keep"
ACTION_UPDATE: Final = "update"
ACTION_BOUNDARY: Final = "boundary"

REASON_INPUT: Final = "input"
REASON_OUTPUT: Final = "output"
REASON_DERIVED: Final = "derived"

KEY_PROTOCOL_VERSION: Final = "protocol_version"
KEY_REQUEST_ID: Final = "request_id"
KEY_EVENT_TYPE: Final = "event_type"
KEY_ERROR: Final = "error"
KEY_SCHEMA_VERSION: Final = "schema_version"
KEY_KIND: Final = "kind"
KEY_MESSAGE: Final = "message"
KEY_SAFE_TRACEBACK: Final = "safe_traceback"
KEY_SOURCE: Final = "source"
KEY_RESULT: Final = "result"
KEY_DATA: Final = "data"
KEY_RECORD: Final = "record"
KEY_METRIC: Final = "metric"
KEY_NAME: Final = "name"
KEY_VALUE: Final = "value"
KEY_UNIT: Final = "unit"
KEY_DIRECTION: Final = "direction"
KEY_TIMESTAMP: Final = "timestamp"
KEY_EVENTS: Final = "events"
KEY_ARTIFACT: Final = "artifact"
KEY_PATH: Final = "path"
KEY_VERSION: Final = "version"
KEY_METADATA: Final = "metadata"
KEY_INPUTS: Final = "inputs"
KEY_OUTPUTS: Final = "outputs"
KEY_RUN_ID: Final = "run_id"
KEY_SEED: Final = "seed"
KEY_PARAMS: Final = "params"
KEY_TARGET: Final = "target"
KEY_REGISTRY_SNAPSHOT: Final = "registry_snapshot"
KEY_ENVIRONMENT: Final = "environment"
KEY_PYTHON: Final = "python"
KEY_PLATFORM: Final = "platform"
KEY_MACHINE: Final = "machine"
KEY_PROCESSOR: Final = "processor"
KEY_METRICS: Final = "metrics"
KEY_ARTIFACTS: Final = "artifacts"
KEY_REF: Final = "ref"
KEY_REFERENCE: Final = "reference"
KEY_PIPELINE: Final = "pipeline"
KEY_STAGES: Final = "stages"
KEY_SINKS: Final = "sinks"
KEY_STEP: Final = "step"
KEY_STEPS: Final = "steps"
KEY_REASON: Final = "reason"
KEY_INDEX: Final = "index"
KEY_STUDY: Final = "study"
KEY_EXPERIMENTS: Final = "experiments"
KEY_EXPERIMENT: Final = "experiment"
KEY_WORKFLOW: Final = "workflow"
KEY_DATASET: Final = "dataset"
KEY_RECORDS: Final = "records"
KEY_AUDIT: Final = "audit"
KEY_DROPPED: Final = "dropped"
KEY_REASONS: Final = "reasons"
KEY_INPUT: Final = "input"
KEY_OUTPUT: Final = "output"
KEY_STAGE: Final = "stage"
KEY_EXIT_CODE: Final = "exit_code"
KEY_TIMED_OUT: Final = "timed_out"

DIR_OUTPUTS: Final = "outputs"
DIR_GENERATED: Final = "generated"
DIR_TABLES: Final = "tables"
DIR_EXTERNAL: Final = "external"
DIR_WORKSPACE: Final = "workspace"
DIR_ARTIFACTS: Final = "artifacts"
DIR_DATASET: Final = "dataset"
DIR_AUDIT: Final = "audit"
DIR_WORKSPACES: Final = "workspaces"
DIR_RESOURCES: Final = "resources"

FILE_RUN_MANIFEST: Final = "run-manifest.json"
FILE_SUMMARY_JSON: Final = "summary.json"
FILE_DROP_REASONS: Final = "drop_reasons.csv"
FILE_STAGE_SUMMARY: Final = "stage_summary.csv"
FILE_SOURCE_SUMMARY: Final = "source_summary.csv"
FILE_STDOUT: Final = "stdout.log"
FILE_STDERR: Final = "stderr.log"

CSV_DROP_REASONS_HEADER: Final = ("reason", "count")
CSV_STAGE_SUMMARY_HEADER: Final = ("stage", "input", "output")
CSV_SOURCE_SUMMARY_HEADER: Final = ("source", "records")

MAX_ARTIFACT_NAME_LEN: Final = 180
ARTIFACT_PREFIX_LEN: Final = 163
ARTIFACT_HASH_LEN: Final = 16

ERROR_RUN_DIR: Final = "runtime execution requires a resolved run_dir"
ERROR_CACHE_DIR: Final = "runtime execution requires a resolved cache_dir"
ERROR_TARGET_MISSING: Final = "execute request missing target"
ERROR_OUTPUT_PATH: Final = "output path must be relative and remain below output_dir"
ERROR_PARAM_STRING: Final = "parameter {name!r} must be a string"
ERROR_PARAM_INT: Final = "parameter {name!r} must be an integer"
ERROR_PARAM_PATH: Final = "parameter {name!r} must be a path"
ERROR_INPUT_MISSING: Final = "input artifact does not exist: {path}"
ERROR_ARTIFACT_MISSING: Final = "artifact path does not exist: {path}"
ERROR_ARTIFACT_DUPLICATE: Final = "artifact {name!r} already refers to a different path"
ERROR_EXTERNAL_NAME: Final = "invalid external command name: {name!r}"
ERROR_WORKSPACE_SOURCE: Final = "external workspace source does not exist: {path}"
ERROR_EXTERNAL_PATH: Final = "external path must be a non-empty relative path: {path!r}"
ERROR_MAPPING: Final = "{label} must be a mapping"
ERROR_NUMERIC: Final = "{label} must be numeric"
ERROR_WORKFLOW_TARGET: Final = "workflow execution missing target"
ERROR_WORKFLOW_STEPS: Final = "workflow {name!r} does not declare steps"
ERROR_WORKFLOW_STEP_OBJECT: Final = "workflow step metadata must be an object"
ERROR_DATASET_TARGET: Final = "dataset execution missing target"
ERROR_AUDIT_STAGES: Final = "audit stages must be a list"
ERROR_DATASET_SINKS: Final = "dataset sinks metadata must be a list"
ERROR_REF: Final = "invalid {kind} reference: {value!r}"
ERROR_SOURCE_CALLABLE: Final = "source must be callable or implement read(ctx)"
ERROR_BATCH_APPLY: Final = "batch stage must implement apply(records)"
ERROR_BATCH_OUTPUT: Final = "batch stage output must be iterable"
ERROR_STAGE_CALLABLE: Final = (
    "pipeline stage must be callable or implement apply(record, ctx)"
)
ERROR_SINK_CALLABLE: Final = "sink must be callable or implement write(records, ctx)"
ERROR_COMPONENT_REF: Final = "component reference must be kind:name, got {value!r}"
ERROR_LOADER_MISSING: Final = "no loader registered for loader:{name}"
ERROR_LOADER_LOAD: Final = "loader:{name} does not implement .load(path)"
