from __future__ import annotations

from pathlib import Path
from datetime import datetime
from typing import Iterable, Literal, Mapping, Sequence, overload

JobStatus = Literal["running", "completed", "failed", "cancelled"]
IdeaStatus = Literal["idea", "planned", "running", "validated", "rejected", "published"]

class EffectiveConfig:
    @property
    def project_name(self) -> str: ...
    @property
    def root(self) -> Path: ...
    def to_json(self) -> str: ...

class RegistryRecord:
    def __init__(
        self,
        kind: str,
        name: str,
        version: str,
        module: str,
        qualname: str,
        source: Path,
        tags: list[str] | None = None,
        description: str = "",
        metadata: str | None = None,
    ) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def name(self) -> str: ...
    def to_json(self) -> str: ...

class Registry:
    def __init__(self) -> None: ...
    def insert(self, record: RegistryRecord) -> None: ...
    def to_json(self) -> str: ...

class ProjectCore:
    def __init__(self, name: str, root: Path | None = None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def root(self) -> Path: ...
    def register(
        self,
        kind: str,
        name: str,
        module: str,
        qualname: str,
        source: Path,
        description: str,
        metadata_json: str,
        callable: object,
        version: str = "1",
        tags: list[str] | None = None,
    ) -> None: ...
    def set_component_extras(
        self,
        kind: str,
        name: str,
        schema: object | None = None,
        requirements_json: str | None = None,
    ) -> None: ...
    def bind_callable(self, kind: str, name: str, callable: object) -> None: ...
    def records_json(self) -> str: ...
    def record_json(self, kind: str, name: str) -> str: ...
    def resolve(self, kind: str, name: str) -> object: ...
    def schema(self, kind: str, name: str) -> object | None: ...
    def requirements_json(self, kind: str, name: str) -> str | None: ...
    def resolve_config(
        self,
        reference: str,
        overrides_json: str = "{}",
        strict: bool = False,
    ) -> object: ...

class ComponentSpec:
    def __init__(self, reference: str, params: object | None = None) -> None: ...
    @classmethod
    def empty(cls, reference: str) -> ComponentSpec: ...
    @classmethod
    def from_value(cls, value: object) -> ComponentSpec: ...
    @property
    def ref(self) -> str: ...
    @property
    def params(self) -> dict[str, object]: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

class Requirements:
    def __init__(
        self,
        model_outputs: Sequence[str] | None = None,
        model_heads: Sequence[str] | None = None,
        batch_fields: Sequence[str] | None = None,
        capabilities: Sequence[str] | None = None,
        artifacts: Sequence[str] | None = None,
    ) -> None: ...
    @property
    def model_outputs(self) -> tuple[str, ...]: ...
    @property
    def model_heads(self) -> tuple[str, ...]: ...
    @property
    def batch_fields(self) -> tuple[str, ...]: ...
    @property
    def capabilities(self) -> tuple[str, ...]: ...
    @property
    def artifacts(self) -> tuple[str, ...]: ...
    def merge(self, other: Requirements) -> Requirements: ...
    def only(self, *fields: str) -> Requirements: ...
    def without(self, *fields: str) -> Requirements: ...
    def to_dict(self) -> dict[str, list[str]]: ...

class ComponentContract:
    def __init__(
        self,
        requires: Requirements | None = None,
        provides: Requirements | None = None,
    ) -> None: ...
    @property
    def requires(self) -> Requirements: ...
    @property
    def provides(self) -> Requirements: ...
    def merge(self, other: ComponentContract) -> ComponentContract: ...
    def to_dict(self) -> dict[str, dict[str, list[str]]]: ...

class MissingRequirements:
    def __init__(
        self,
        model_outputs: Sequence[str] | None = None,
        model_heads: Sequence[str] | None = None,
        batch_fields: Sequence[str] | None = None,
        capabilities: Sequence[str] | None = None,
        artifacts: Sequence[str] | None = None,
    ) -> None: ...
    @property
    def ok(self) -> bool: ...
    @property
    def model_outputs(self) -> tuple[str, ...]: ...
    @property
    def model_heads(self) -> tuple[str, ...]: ...
    @property
    def batch_fields(self) -> tuple[str, ...]: ...
    @property
    def capabilities(self) -> tuple[str, ...]: ...
    @property
    def artifacts(self) -> tuple[str, ...]: ...
    def raise_if_any(self, label: str = "component contract") -> None: ...
    def to_dict(self) -> dict[str, list[str]]: ...

class MissingRequirementsError(ValueError): ...

class ComponentUse:
    def __init__(self, reference: str) -> None: ...
    @property
    def ref(self) -> str: ...
    def to_json(self) -> str: ...

class DataDecision:
    @property
    def action(self) -> str: ...
    @property
    def record(self) -> object | None: ...
    @property
    def reason(self) -> str | None: ...
    @property
    def kind(self) -> str | None: ...
    def to_json(self) -> str: ...

class DataBoundary:
    def __init__(self, value: object, kind: str) -> None: ...
    @property
    def value(self) -> object: ...
    @property
    def kind(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...
    def to_json(self) -> str: ...

class NativeTextFilter:
    def __init__(self, rules: Sequence[object]) -> None: ...
    def apply(self, record: object, _ctx: object | None = None) -> DataDecision: ...

class NativeSimhashDedup:
    def __init__(self, field: str, source_field: str, exact_min_words: int, source_exact_min_words: Mapping[str, int], near_enabled: bool, near_min_words: int, near_hamming_threshold: int, near_max_bucket_size: int) -> None: ...
    def apply(self, records: object, _ctx: object | None = None) -> list[object]: ...

class NativeDocumentAssembler:
    def __init__(self, text_field: str, source_field: str, origin_field: str, target_word_budget: int, source_word_targets: Mapping[str, int], min_document_words: int, max_document_chars: int, max_document_lines: int) -> None: ...
    def apply(self, records: object, _ctx: object | None = None) -> list[dict[str, object]]: ...

class SubstituteStage:
    def __init__(self, field: str, old: str, new: str) -> None: ...
    def apply(self, record: object, _ctx: object | None = None) -> DataDecision: ...

class ClassifyStage:
    def __init__(self, field: str, labels: Mapping[str, str]) -> None: ...
    def apply(self, record: object, _ctx: object | None = None) -> DataDecision: ...

class ThresholdStage:
    def __init__(
        self,
        field: str,
        minimum: float | None = None,
        maximum: float | None = None,
    ) -> None: ...
    def apply(self, record: object, _ctx: object | None = None) -> DataDecision: ...

class MaterializeReport:
    @property
    def written_records(self) -> int: ...
    @property
    def dropped_records(self) -> int: ...
    def to_json(self) -> str: ...

class JsonlSource:
    def __init__(self, path: Path) -> None: ...
    @property
    def path(self) -> Path: ...
    def read(self, _ctx: object | None = None) -> list[dict[str, object]]: ...

class JsonlSink:
    def __init__(self, path: Path) -> None: ...
    @property
    def path(self) -> Path: ...
    def write(self, records: object, _ctx: object | None = None) -> Path: ...

class ExternalPath:
    def __init__(self, path: str, name: str) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def name(self) -> str: ...
    def validate(self) -> None: ...
    def to_json(self) -> str: ...

class ExternalWorkspace:
    def __init__(
        self,
        source_param: str,
        default_source: str,
        ignored: Sequence[str] | None = None,
        cached: Sequence[ExternalPath] | None = None,
        outputs: Sequence[ExternalPath] | None = None,
    ) -> None: ...
    @property
    def source_param(self) -> str: ...
    @property
    def default_source(self) -> str: ...
    @property
    def ignored(self) -> list[str]: ...
    @property
    def cached(self) -> list[ExternalPath]: ...
    @property
    def outputs(self) -> list[ExternalPath]: ...
    def validate(self) -> None: ...
    def to_json(self) -> str: ...

class ExternalCommand:
    def __init__(
        self,
        args: Sequence[str],
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
        timeout_seconds: int | None = None,
        output_root: Path | None = None,
        artifacts: Sequence[str] | None = None,
    ) -> None: ...
    @property
    def args(self) -> list[str]: ...
    @property
    def cwd(self) -> Path | None: ...
    @property
    def env(self) -> dict[str, str]: ...
    @property
    def timeout_seconds(self) -> int | None: ...
    @property
    def output_root(self) -> Path | None: ...
    @property
    def artifacts(self) -> list[str]: ...
    def validate(self) -> None: ...
    def run(self) -> ExternalResult: ...
    def replace(
        self,
        args: Sequence[str] | None = None,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
        timeout_seconds: int | None = None,
        output_root: Path | None = None,
        artifacts: Sequence[str] | None = None,
    ) -> ExternalCommand: ...
    def to_json(self) -> str: ...

class ExternalResult:
    @property
    def exit_code(self) -> int | None: ...
    @property
    def stdout(self) -> str: ...
    @property
    def stderr(self) -> str: ...
    @property
    def timed_out(self) -> bool: ...
    def to_json(self) -> str: ...

class Metric:
    def __init__(
        self,
        name: str,
        value: float,
        unit: str | None = None,
        direction: str | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> float: ...

class ResultBundle:
    def __init__(self) -> None: ...
    def to_json(self) -> str: ...

class FileArtifact:
    def __init__(
        self,
        name: str,
        path: Path,
        kind: str = "file",
        version: str = "1",
        metadata: Mapping[str, object] | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> Path: ...
    @property
    def kind(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def metadata(self) -> dict[str, object]: ...
    def to_event_payload(self) -> dict[str, object]: ...
    def to_json(self) -> str: ...

class FigureArtifact(FileArtifact): ...
class TableArtifact(FileArtifact): ...
class LogArtifact(FileArtifact): ...

class ResultSchema:
    def __init__(
        self,
        name: str,
        fields: Mapping[str, str] | None = None,
        version: str = "1",
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def fields(self) -> dict[str, str]: ...
    @property
    def version(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

class RunRecord:
    @property
    def run_id(self) -> str: ...
    @property
    def path(self) -> Path: ...
    @property
    def manifest(self) -> dict[str, object]: ...
    @property
    def params(self) -> dict[str, object]: ...
    @property
    def metrics(self) -> dict[str, float]: ...

class RunQuery:
    def __init__(self, root: Path | None = None) -> None: ...
    @property
    def root(self) -> Path: ...
    def find(
        self,
        *,
        target: str | None = None,
        seed: int | None = None,
    ) -> list[RunRecord]: ...
    def all(self) -> list[RunRecord]: ...

class RunHandle:
    @property
    def run_id(self) -> str: ...
    @property
    def path(self) -> Path: ...
    @property
    def status(self) -> str: ...
    @property
    def result(self) -> object: ...
    def metrics(self) -> dict[str, object]: ...
    def artifact(self, name: str) -> Path: ...

class RuntimeContext:
    def __init__(
        self,
        run_id: str | None = None,
        run_dir: Path | None = None,
        cache_dir: Path | None = None,
        project_root: Path | None = None,
        params_json: str = "{}",
        seed: int | None = None,
        strict: bool = False,
    ) -> None: ...
    def log_metric(self, name: str, value: float) -> None: ...
    def log_metrics(self, metrics: dict[str, float]) -> None: ...
    def metrics_json(self) -> str: ...
    def artifacts_json(self) -> str: ...
    def logs_json(self) -> str: ...
    def host_event_lines(self, request_id: str, result: object) -> list[str]: ...
    def params_json(self) -> str: ...
    def save_artifact(
        self,
        first: str | Path,
        second: str | Path | None = None,
        kind: str = "file",
        version: str = "1",
        metadata: object | None = None,
        inputs: Sequence[str] | None = None,
    ) -> Path: ...
    def save_file(self, name: str, path: Path) -> Path: ...
    def save_dir(self, name: str, path: Path) -> Path: ...
    def write_manifest(
        self,
        name: str | Path,
        payload: object,
        *,
        artifact: str | None = None,
        kind: str = "file",
    ) -> Path: ...
    def save_table(self, name: str, rows: object) -> Path: ...
    def note(self, text: str) -> None: ...
    def log(self, text: str) -> None: ...
    def report_progress(
        self,
        phase: str,
        component: str = "",
        state: str = "running",
        processed: int = 0,
        total: int | None = None,
        detail: str = "",
    ) -> None: ...
    def run(
        self,
        target: str,
        params: dict[str, object] | None = None,
        *,
        seed: int | None = None,
        strict: bool | None = None,
        allow_failure: bool = False,
    ) -> RunHandle: ...
    def run_external(
        self,
        name_or_command: str | ExternalCommand,
        command: ExternalCommand | None = None,
    ) -> ExternalResult: ...
    def external_workspace(
        self,
        name: str,
        spec: ExternalWorkspace,
        params: object | None = None,
    ) -> object: ...
    def str_param(self, name: str, default: str | None = None) -> str: ...
    def int_param(self, name: str, default: int | None = None) -> int: ...
    def optional_int_param(self, name: str) -> int | None: ...
    def bool_param(self, name: str, default: bool | None = None) -> bool: ...
    def number_param(self, name: str, default: float | None = None) -> float: ...
    def path_param(self, name: str, default: Path | None = None) -> Path: ...
    def overrides(
        self,
        exclude: Sequence[str] | None = None,
        path_prefix: str | None = None,
        passthrough_roots: Sequence[str] | None = None,
    ) -> dict[str, object]: ...
    def config(
        self,
        schema: object,
        base: object,
        *,
        exclude: Sequence[str] | None = None,
        path_prefix: str | None = None,
        passthrough_roots: Sequence[str] | None = None,
        strict: bool = False,
    ) -> object: ...
    def output_path(self, value: Path) -> Path: ...
    @property
    def params(self) -> dict[str, object]: ...
    @property
    def output_dir(self) -> Path | None: ...
    @property
    def run_id(self) -> str | None: ...
    @property
    def run_dir(self) -> Path | None: ...
    @property
    def cache_dir(self) -> Path | None: ...
    @property
    def project_root(self) -> Path: ...
    @property
    def seed(self) -> int | None: ...

class RetentionPolicy:
    def __init__(
        self,
        keep_last: int | None = None,
        keep_milestones: bool = True,
    ) -> None: ...

class CheckpointRecord:
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> Path: ...
    @property
    def step(self) -> int: ...
    @property
    def metric(self) -> float | None: ...
    @property
    def milestone(self) -> bool: ...

class CheckpointManager:
    def __init__(
        self,
        root: Path,
        serializer: object,
        retention: RetentionPolicy | None = None,
    ) -> None: ...
    def save(
        self,
        name: str,
        state: object,
        step: int,
        metric: float | None = None,
        milestone: bool = False,
    ) -> CheckpointRecord: ...
    def load(self, reference: str | Path = "latest") -> object: ...
    def records(self) -> list[CheckpointRecord]: ...
    def prune(self) -> None: ...

class MetricComparison:
    @property
    def mean_a(self) -> float: ...
    @property
    def mean_b(self) -> float: ...
    @property
    def delta(self) -> float: ...
    @property
    def effect_size(self) -> float | None: ...
    @property
    def confidence_interval(self) -> tuple[float, float] | None: ...
    def to_json(self) -> str: ...

class RunDirectory:
    def __init__(self, id: str) -> None: ...
    @property
    def id(self) -> str: ...

class ArtifactManifest:
    def to_json(self) -> str: ...

class ArtifactStore:
    def __init__(self, root: Path) -> None: ...
    def promote(
        self, source: Path, kind: str, name: str, version: str
    ) -> ArtifactManifest: ...

class CacheEntry:
    @property
    def path(self) -> Path: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def bytes(self) -> int: ...
    @property
    def kind(self) -> str: ...

class BudgetEstimate:
    @property
    def jobs(self) -> int: ...
    @property
    def total_seconds(self) -> float: ...
    @property
    def total_storage_gb(self) -> float: ...

class BaselineEntry:
    def __init__(
        self,
        name: str,
        metric: str,
        value: float,
        description: str | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def metric(self) -> str: ...
    @property
    def value(self) -> float: ...
    @property
    def description(self) -> str | None: ...

class BaselineStore:
    def __init__(self) -> None: ...
    def add(self, entry: BaselineEntry) -> None: ...
    def list(self) -> list[BaselineEntry]: ...

class JobRecord:
    def __init__(
        self,
        id: str,
        command: str,
        status: JobStatus,
        log_path: Path,
        exit_code: int | None = None,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def command(self) -> str: ...
    @property
    def status(self) -> JobStatus: ...
    @property
    def log_path(self) -> Path: ...
    @property
    def exit_code(self) -> int | None: ...

class DecisionEntry:
    def __init__(
        self,
        text: str,
        selected_run: str | None = None,
        criteria: Mapping[str, str] | None = None,
    ) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def selected_run(self) -> str | None: ...
    @property
    def criteria(self) -> dict[str, object]: ...
    @property
    def created_at(self) -> datetime: ...

class NegativeResultEntry:
    def __init__(self, hypothesis: str, tried: str, reason: str) -> None: ...
    @property
    def hypothesis(self) -> str: ...
    @property
    def tried(self) -> str: ...
    @property
    def reason(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...

class IdeaEntry:
    def __init__(self, text: str, status: IdeaStatus = "idea") -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def status(self) -> IdeaStatus: ...
    @property
    def created_at(self) -> datetime: ...

class NoteEntry:
    def __init__(self, run_id: str, text: str) -> None: ...
    @property
    def run_id(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...

class Unit:
    def __init__(self, name: str, symbol: str, dimension: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def symbol(self) -> str: ...
    @property
    def dimension(self) -> str: ...

class UnitRegistry:
    def __init__(self) -> None: ...
    def add(self, unit: Unit) -> None: ...
    @property
    def units(self) -> dict[str, Unit]: ...

class Assumption:
    def __init__(self, text: str, evidence: str | None = None) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def evidence(self) -> str | None: ...

class Threat:
    def __init__(self, text: str, mitigation: str | None = None) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def mitigation(self) -> str | None: ...

class SecretHit:
    @property
    def key(self) -> str: ...
    @property
    def reason(self) -> str: ...

class PiiHit:
    @property
    def kind(self) -> str: ...
    @property
    def value(self) -> str: ...

class LicenseManifest:
    def __init__(self, name: str, license: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def license(self) -> str: ...

class LicenseCompatibilitySummary:
    @property
    def compatible(self) -> bool: ...
    @property
    def warnings(self) -> list[str]: ...

class PolicyViolation:
    @property
    def rule(self) -> str: ...
    @property
    def subject(self) -> str: ...

class LabPolicy:
    def __init__(
        self, forbidden_env_patterns: Sequence[str] | None = None
    ) -> None: ...
    @property
    def forbidden_env_patterns(self) -> list[str]: ...
    def check_env(self, env: Mapping[str, str]) -> list[PolicyViolation]: ...

class ProductionPolicy:
    def __init__(self, strict: bool) -> None: ...
    @property
    def strict(self) -> bool: ...

def cli_main() -> int: ...
def _failed_host_event_line(
    request_id: str,
    kind: str,
    message: str,
    safe_traceback: str,
    source: str,
) -> str: ...
def find_project_root(path: Path) -> Path: ...
def load_config(root: Path | None = None) -> EffectiveConfig: ...
def resolve_config_document(
    root: Path,
    name: str,
    overrides_json: str = "{}",
    suffix: str = ".yaml",
    require_explicit_paths: bool = True,
) -> str: ...
def list_config_documents(root: Path, suffix: str = ".yaml") -> list[str]: ...
def validate_config_documents(root: Path, suffix: str = ".yaml") -> str: ...
def diff_config_documents(left_json: str, right_json: str) -> str: ...
def cache_path(root: Path | None = None) -> Path: ...
def list_cache(root: Path | None = None) -> list[CacheEntry]: ...
def cache_size(entries: Sequence[CacheEntry]) -> int: ...
def cache_key(value: object) -> str: ...
def runtime_cache_path(ctx: object, *parts: str) -> Path: ...
def read_jsonl(path: Path) -> list[dict[str, object]]: ...
def write_jsonl_atomic(path: Path, rows: Iterable[Mapping[str, object]]) -> None: ...
def write_through_jsonl_atomic(
    path: Path,
    rows: Iterable[object],
    encode: object,
) -> list[object]: ...
def estimate_budget(
    jobs: int, seconds_per_job: float, storage_gb_per_job: float
) -> BudgetEstimate: ...
def estimate_required_repetitions(
    effect_size: float, variance: float, alpha: float, power: float
) -> int: ...
def redact_secrets(env: Mapping[str, str]) -> dict[str, str]: ...
def scan_for_secrets(text: str) -> list[SecretHit]: ...
def scan_for_pii(text: str) -> list[PiiHit]: ...
def check_compatibility(
    manifests: Sequence[LicenseManifest],
) -> LicenseCompatibilitySummary: ...
def assert_valid_run_dir(path: Path) -> None: ...
def assert_metric_exists(path: Path, name: str) -> None: ...
def resolve_data_document(
    root: Path,
    name: str,
    overrides_json: str = "{}",
    require_explicit_paths: bool = True,
) -> str: ...
def list_data_documents(root: Path) -> list[str]: ...
def validate_data_documents(root: Path) -> str: ...
def apply_overrides(value: object, overrides: object, *, strict: bool = False) -> object: ...
@overload
def read_json_manifest(
    path: Path,
    *,
    required_fields: Sequence[str] | None = None,
    schema: None = None,
) -> dict[str, object]: ...
@overload
def read_json_manifest(
    path: Path,
    *,
    required_fields: Sequence[str] | None = None,
    schema: type[object],
) -> object: ...
def bundle_from_metrics(metrics: Mapping[str, float]) -> ResultBundle: ...
def data_keep(record: object) -> DataDecision: ...
def data_update(record: object, reason: str | None = None) -> DataDecision: ...
def data_drop(reason: str) -> DataDecision: ...
def data_boundary(value: object, kind: str) -> DataDecision: ...
def substitute(field: str, old: str, new: str) -> SubstituteStage: ...
def classify(field: str, labels: Mapping[str, str]) -> ClassifyStage: ...
def threshold(
    field: str,
    minimum: float | None = None,
    maximum: float | None = None,
) -> ThresholdStage: ...
def component_spec_from_value(value: object) -> ComponentSpec: ...
def collect_requirements(values: Iterable[Requirements]) -> Requirements: ...
def collect_component_requirements(
    lookup: object,
    kind: str,
    specs: Iterable[object],
) -> Requirements: ...
def collect_contracts(values: Iterable[ComponentContract]) -> ComponentContract: ...
def missing_requirements(
    required: Requirements,
    provided: Requirements,
    *,
    fields: Iterable[str] | None = None,
) -> MissingRequirements: ...
def requirements_from_mapping(value: object) -> Requirements: ...
def materialize_data(
    output_dir: Path,
    decisions: Sequence[DataDecision],
) -> MaterializeReport: ...
def materialize_records(
    records: Sequence[object],
    stages: Sequence[object],
) -> list[object]: ...
def execute_dataset(
    name: str,
    source: object,
    stages: Sequence[tuple[str, object, object]],
    sinks: Sequence[object],
    ctx: RuntimeContext,
) -> str: ...
def run_external_command(
    args: list[str],
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
    timeout_seconds: int | None = None,
    stdout_path: Path | None = None,
    stderr_path: Path | None = None,
) -> str: ...
def add_lineage_edge(
    root: Path,
    source: str,
    target: str,
    reason: str | None = None,
) -> None: ...
def lineage_for(
    root: Path,
    reference: str,
) -> dict[str, list[str]]: ...
def compare_metric_arrays(a: list[float], b: list[float]) -> MetricComparison: ...
def paired_bootstrap(
    a: list[float],
    b: list[float],
    samples: int = 10_000,
    confidence: float = 0.95,
    seed: int = 0,
) -> MetricComparison: ...
def write_markdown_report(
    path: Path,
    title: str,
    fields: Mapping[str, object],
) -> Path: ...
def write_card(
    path: Path,
    title: str,
    sections: Mapping[str, Mapping[str, object]],
) -> Path: ...
